# Generated by Django 5.1.1 on 2024-09-06 12:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(choices=[('Yoga', 'Yoga'), ('Gym', 'Gym'), ('Dance', 'Dance')], max_length=10)),
                ('date', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField()),
                ('booked_slots', models.PositiveIntegerField(default=0)),
                ('waiting_list', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('booked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.class')),
            ],
        ),
    ]
