# Generated by Django 5.1.1 on 2024-09-06 19:29

import queue
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_booking_id_alter_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default=queue.Full, max_length=100),
        ),
    ]
