"""
Django settings for bookclass project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
#import pymysql
#pymysql.install_as_MySQLdb()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'trmgbdim3z^hzcg3r6*-l1lm%fs$&7!7pz(8x3zbv=jdgim47e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['https://fitness-slot-booking-systemm.onrender.com']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'classes',         # Your custom app for managing class bookings
    'rest_framework',  # Django REST framework for API endpoints
    'corsheaders',     # To allow cross-origin requests from your React frontend
    'django_extensions', # To allow for shell_plus  -- to show urls of the project
]

MIDDLEWARE = [
    # Place corsheaders middleware at the top so that it can add the CORS headers
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',  # Make sure this comes after CorsMiddleware
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Whitenoise for serving static files
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bookclass.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # You can add template directories here
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bookclass.wsgi.application'

# Database configuration for MySQL
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'yoga',             # Your MySQL database name
        'USER': 'jeevan',           # Your MySQL username
        'PASSWORD': '9392',         # Your MySQL password
        'HOST': 'localhost',        # MySQL server address
        'PORT': '3306',             # Default MySQL port
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization settings
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files settings
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Note: If you're serving your React build from Django, make sure the build exists.
# Otherwise, you might get warnings about the path below.
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'frontend/build/static')
]

# Django REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

# Default auto field setting (note: Django 2.2 doesn't enforce this, but it's okay to include)
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings to allow your React app (running on localhost:3000) to communicate with Django
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]
